apiVersion: v1
kind: Service
metadata:
  name: helloworld-svc
  labels:
    app: helloworld
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: helloworld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-dep
  labels:
    app: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: ghaideraksdemoregistry.azurecr.io/demo/helloworld
        ports:
        - containerPort: 80
